files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D26088F21E3A03BD0AF1C72C387BDD81
  logicalPath: config\pic32mk_mcm_curiosity_pro\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: D26088F21E3A03BD0AF1C72C387BDD81
- generatedChecksum: EC410AF32A00CC5E9DF0F879297B47F1
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EC410AF32A00CC5E9DF0F879297B47F1
- generatedChecksum: FD3C67B6397EBC0A74AF969863E46985
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: FD3C67B6397EBC0A74AF969863E46985
- generatedChecksum: 2E1A7B32EFD35C0C56EBBBEBC00D9FD2
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2E1A7B32EFD35C0C56EBBBEBC00D9FD2
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 9F977ADA60E725E676D02F044CF4F035
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9F977ADA60E725E676D02F044CF4F035
- generatedChecksum: BA317C94A6E4AC6796136FB5850DB9CA
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: BA317C94A6E4AC6796136FB5850DB9CA
- generatedChecksum: 7B29B2019511C46F2432BA7318521156
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7B29B2019511C46F2432BA7318521156
- generatedChecksum: 1E86F77B31D7258FBF1A2CB54235EDE9
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\uart
  name: plib_uart6.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1E86F77B31D7258FBF1A2CB54235EDE9
- generatedChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\console
  name: sys_console.c
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20C22A19D5DC74DEBFC4CCCA83B6F603
- generatedChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\console
  name: sys_console_local.h
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5BA0902794A8669B3FE37E8A8BEE9D65
- generatedChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\console
  name: sys_console_uart.c
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: CA5E9B63704372DE5FBC0BDC006B16C3
- generatedChecksum: 767495C6A39617A915D8107093DC1A72
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\console
  name: sys_console_uart.h
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 767495C6A39617A915D8107093DC1A72
- generatedChecksum: 5D10B9438117B64220180660AB022150
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\console
  name: sys_console_uart_definitions.h
  physicalPath: system\console\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5D10B9438117B64220180660AB022150
- generatedChecksum: 68C0D499B9EDAA3BFD7E131A48514212
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\debug
  name: sys_debug.c
  physicalPath: system\debug\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 68C0D499B9EDAA3BFD7E131A48514212
- generatedChecksum: B8C6C7356AC7841AECC7C779040F745C
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\debug
  name: sys_debug_local.h
  physicalPath: system\debug\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: B8C6C7356AC7841AECC7C779040F745C
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mk_mcm_curiosity_pro\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 60CCF2FCB84A0FA9AA8C1607725D47A4
  logicalPath: config\pic32mk_mcm_curiosity_pro\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 60CCF2FCB84A0FA9AA8C1607725D47A4
- generatedChecksum: 4855B5EA5BE394CEACBC41B6FEAD2183
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4855B5EA5BE394CEACBC41B6FEAD2183
- generatedChecksum: 7A26D13F5477CD0F1C79509B54DF25C0
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A26D13F5477CD0F1C79509B54DF25C0
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config\pic32mk_mcm_curiosity_pro\driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config\pic32mk_mcm_curiosity_pro\driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mk_mcm_curiosity_pro\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\pic32mk_mcm_curiosity_pro\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config\pic32mk_mcm_curiosity_pro\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
- generatedChecksum: D1FCD99E5A0E427B38B8452FE85F97FD
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: D1FCD99E5A0E427B38B8452FE85F97FD
- generatedChecksum: 8B8113DCA7121F05EE4A7CC283544215
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\uart
  name: plib_uart6.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 8B8113DCA7121F05EE4A7CC283544215
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mk_mcm_curiosity_pro\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 0525B31317EA9CBFEC119F7C1B8987DA
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\console
  name: sys_console.h
  physicalPath: system\console
  security: NON_SECURE
  type: HEADER
  userChecksum: 0525B31317EA9CBFEC119F7C1B8987DA
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\pic32mk_mcm_curiosity_pro\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\pic32mk_mcm_curiosity_pro\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\pic32mk_mcm_curiosity_pro\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\pic32mk_mcm_curiosity_pro\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 51008F94CB120E2E6113CD8B5B91734A
  logicalPath: config\pic32mk_mcm_curiosity_pro
  name: p32MK1024MCM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 51008F94CB120E2E6113CD8B5B91734A
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;../src/packs/PIC32MK1024MCM100_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
