format_version: v1.0
type: UniqueComponent
attributes: {id: i2c2}
children:
- type: Symbols
  children:
  - type: Integer
    attributes: {id: BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '595'}
  - type: Integer
    attributes: {id: I2CS_RISE_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '18'}
  - type: Integer
    attributes: {id: I2CS_SETUP_TIME_CORE_TIMER_CNTS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '6'}
  - type: Integer
    attributes: {id: I2C_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: '60000000'}
  - type: Combo
    attributes: {id: I2C_OPERATING_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c2, value: Master}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: I2C2_I2C}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_i2c_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2c_I2C_dependency}
- type: ElementPosition
  attributes: {x: '3', y: '210', id: i2c2}
