files:
- generatedChecksum: E4894B6355AF41AED546E4C6C20005C1
  logicalPath: FreeRTOS/Source
  name: FreeRTOS_tasks.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: E4894B6355AF41AED546E4C6C20005C1
- generatedChecksum: 5B0ABC7040175601AE3BFF86683325BD
  logicalPath: config/pic32mk_mcj_curiosity_pro/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5B0ABC7040175601AE3BFF86683325BD
- generatedChecksum: 4490B523D4D89767AF3FE31B825F7F6D
  logicalPath: FreeRTOS/Source
  name: croutine.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4490B523D4D89767AF3FE31B825F7F6D
- generatedChecksum: 0E0E8AECB67046FEA847B359ACE7A1F6
  logicalPath: FreeRTOS/Source
  name: event_groups.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E0E8AECB67046FEA847B359ACE7A1F6
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: CF89BE92AE72229779903C2E9A760455
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: freertos_hooks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CF89BE92AE72229779903C2E9A760455
- generatedChecksum: 31CEE4650E24C72160696DF93B55B48D
  logicalPath: FreeRTOS/Source/portable/MemMang
  name: heap_1.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MemMang
  security: NON_SECURE
  type: SOURCE
  userChecksum: 31CEE4650E24C72160696DF93B55B48D
- generatedChecksum: C1B4FC788C4AACED54AEBB984030F7D9
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C1B4FC788C4AACED54AEBB984030F7D9
- generatedChecksum: D51C4682C473EAF4080212A50DDD70F3
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D51C4682C473EAF4080212A50DDD70F3
- generatedChecksum: C1E8A87684E987DB4AFF112ACAF95B48
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts_a.S
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C1E8A87684E987DB4AFF112ACAF95B48
- generatedChecksum: 47F98BAFD5D2A077AB529D10DB870AFF
  logicalPath: FreeRTOS/Source
  name: list.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47F98BAFD5D2A077AB529D10DB870AFF
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
  logicalPath: config/pic32mk_mcj_curiosity_pro/osal
  name: osal_freertos.c
  physicalPath: osal
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
- generatedChecksum: 5EDD71407F2E1FAF70799BA51E1EA385
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5EDD71407F2E1FAF70799BA51E1EA385
- generatedChecksum: 22505D1D99523B27BFE339365989CC43
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 22505D1D99523B27BFE339365989CC43
- generatedChecksum: 827E08CE3DB6E3E304AF209989164C59
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 827E08CE3DB6E3E304AF209989164C59
- generatedChecksum: 8DC27DDBD16DC2B9AB8BD322F1C1B687
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8DC27DDBD16DC2B9AB8BD322F1C1B687
- generatedChecksum: 0E851159CFF7B40028D295108F0F7474
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MK
  name: port.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E851159CFF7B40028D295108F0F7474
- generatedChecksum: DF45E3DDDEC2F56707A9CBFBE9B8F3FD
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MK
  name: port_asm.S
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK
  security: NON_SECURE
  type: SOURCE
  userChecksum: DF45E3DDDEC2F56707A9CBFBE9B8F3FD
- generatedChecksum: 13259EE43A731BF0F46EA946229027BF
  logicalPath: FreeRTOS/Source
  name: queue.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13259EE43A731BF0F46EA946229027BF
- generatedChecksum: A9BDA97498BEA85049883F48FB1094A0
  logicalPath: FreeRTOS/Source
  name: stream_buffer.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: A9BDA97498BEA85049883F48FB1094A0
- generatedChecksum: null
  logicalPath: ''
  name: task1_mcj.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task2_mcj.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task3_mcj.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task4_mcj.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: EC8EA0C7CD7EEFE60FB9DA99A4A0DBFC
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EC8EA0C7CD7EEFE60FB9DA99A4A0DBFC
- generatedChecksum: 2811D7C532CEFF995F8697FCED6A1C34
  logicalPath: FreeRTOS/Source
  name: timers.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2811D7C532CEFF995F8697FCED6A1C34
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mk_mcj_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 5E06C8C3B681B9398724569B7DC5AFB8
  logicalPath: FreeRTOS/Source/include
  name: FreeRTOS.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5E06C8C3B681B9398724569B7DC5AFB8
- generatedChecksum: 8DF2A49E7B6CC941FA3776D48DD58736
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: FreeRTOSConfig.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DF2A49E7B6CC941FA3776D48DD58736
- generatedChecksum: E44F224CDF5B12B127F4CF2B074AD35D
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MK
  name: ISR_Support.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK
  security: NON_SECURE
  type: HEADER
  userChecksum: E44F224CDF5B12B127F4CF2B074AD35D
- generatedChecksum: 319C49724C3B44D8BA0262A7F785A4AB
  logicalPath: config/pic32mk_mcj_curiosity_pro/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 319C49724C3B44D8BA0262A7F785A4AB
- generatedChecksum: 7A852268CAA1F0FBB9E75D327532882A
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A852268CAA1F0FBB9E75D327532882A
- generatedChecksum: 4B11D1A616E95BDD37123685C8434FCF
  logicalPath: FreeRTOS/Source/include
  name: croutine.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 4B11D1A616E95BDD37123685C8434FCF
- generatedChecksum: ACD1E87DEFBA5AE33641DACA28AC4D43
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: ACD1E87DEFBA5AE33641DACA28AC4D43
- generatedChecksum: ACB7AD12FD525895ABA47C26F4F9A683
  logicalPath: FreeRTOS/Source/include
  name: deprecated_definitions.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: ACB7AD12FD525895ABA47C26F4F9A683
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: DE52B71A2D274138117243B700F40B11
  logicalPath: FreeRTOS/Source/include
  name: event_groups.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: DE52B71A2D274138117243B700F40B11
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 58875A2FBF6B0502B6D3B8B5C47F3815
  logicalPath: FreeRTOS/Source/include
  name: list.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 58875A2FBF6B0502B6D3B8B5C47F3815
- generatedChecksum: 5D9D0A05D32C97E2E625020E1795C7F1
  logicalPath: FreeRTOS/Source/include
  name: message_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D9D0A05D32C97E2E625020E1795C7F1
- generatedChecksum: A34AAAD9F0BD596E8FF78D86FD64F869
  logicalPath: FreeRTOS/Source/include
  name: mpu_prototypes.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: A34AAAD9F0BD596E8FF78D86FD64F869
- generatedChecksum: 2ECEDD5114F296955777187904C449C7
  logicalPath: FreeRTOS/Source/include
  name: mpu_wrappers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 2ECEDD5114F296955777187904C449C7
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mk_mcj_curiosity_pro/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 167A43EFF8A31441EBF85AC77958A30B
  logicalPath: config/pic32mk_mcj_curiosity_pro/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 167A43EFF8A31441EBF85AC77958A30B
- generatedChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
  logicalPath: config/pic32mk_mcj_curiosity_pro/osal
  name: osal_freertos.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 23F86588C83891551C404C1BA77F9655
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 23F86588C83891551C404C1BA77F9655
- generatedChecksum: 19065312F78B71CF702868AD7B40FF7B
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 19065312F78B71CF702868AD7B40FF7B
- generatedChecksum: E3F9F87FACE403727594E991034A8076
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: E3F9F87FACE403727594E991034A8076
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mcj_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 8DD6C24BF18C96BDC016D9165DF88FEB
  logicalPath: FreeRTOS/Source/include
  name: portable.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DD6C24BF18C96BDC016D9165DF88FEB
- generatedChecksum: 94F2A78A46AC9F36C974B8E7BA09919F
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MK
  name: portmacro.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK
  security: NON_SECURE
  type: HEADER
  userChecksum: 94F2A78A46AC9F36C974B8E7BA09919F
- generatedChecksum: 99A9BD4D90230B49C97BBCEE121C1182
  logicalPath: FreeRTOS/Source/include
  name: projdefs.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 99A9BD4D90230B49C97BBCEE121C1182
- generatedChecksum: F917F55E280C54C23A7541A76AC34225
  logicalPath: FreeRTOS/Source/include
  name: queue.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: F917F55E280C54C23A7541A76AC34225
- generatedChecksum: D7426A4807316E4BB5540458F6F4C68F
  logicalPath: FreeRTOS/Source/include
  name: semphr.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: D7426A4807316E4BB5540458F6F4C68F
- generatedChecksum: 634A3DF879F184ABC5F96107F46AC4B2
  logicalPath: FreeRTOS/Source/include
  name: stack_macros.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 634A3DF879F184ABC5F96107F46AC4B2
- generatedChecksum: A652AC7D4938BE16F535BA3C90C86463
  logicalPath: FreeRTOS/Source/include
  name: stream_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: A652AC7D4938BE16F535BA3C90C86463
- generatedChecksum: 0A58B32A7058D0599EC5F6E3B33D42E6
  logicalPath: FreeRTOS/Source/include
  name: task.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 0A58B32A7058D0599EC5F6E3B33D42E6
- generatedChecksum: null
  logicalPath: ''
  name: task1_mcj.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task2_mcj.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task3_mcj.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: task4_mcj.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 41176F771D22559EFCE82398FCF33668
  logicalPath: FreeRTOS/Source/include
  name: timers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 41176F771D22559EFCE82398FCF33668
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: null
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: D8C84D56283D1E38192D28930F8D71D9
  logicalPath: config/pic32mk_mcj_curiosity_pro
  name: p32MK0512MCJ064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: D8C84D56283D1E38192D28930F8D71D9
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-assembler
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mk_mcj_curiosity_pro;
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-preprocessor
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mk_mcj_curiosity_pro;
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcj_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
