files:
- generatedChecksum: E4894B6355AF41AED546E4C6C20005C1
  logicalPath: FreeRTOS/Source
  name: FreeRTOS_tasks.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: E4894B6355AF41AED546E4C6C20005C1
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app1.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D26088F21E3A03BD0AF1C72C387BDD81
  logicalPath: config/pic32mk_gp_db/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: D26088F21E3A03BD0AF1C72C387BDD81
- generatedChecksum: 4490B523D4D89767AF3FE31B825F7F6D
  logicalPath: FreeRTOS/Source
  name: croutine.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4490B523D4D89767AF3FE31B825F7F6D
- generatedChecksum: 0E0E8AECB67046FEA847B359ACE7A1F6
  logicalPath: FreeRTOS/Source
  name: event_groups.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E0E8AECB67046FEA847B359ACE7A1F6
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mk_gp_db
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: CF89BE92AE72229779903C2E9A760455
  logicalPath: config/pic32mk_gp_db
  name: freertos_hooks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CF89BE92AE72229779903C2E9A760455
- generatedChecksum: 31CEE4650E24C72160696DF93B55B48D
  logicalPath: FreeRTOS/Source/portable/MemMang
  name: heap_1.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MemMang
  security: NON_SECURE
  type: SOURCE
  userChecksum: 31CEE4650E24C72160696DF93B55B48D
- generatedChecksum: 3F20C45547DA70F47ACA0F95C67AFE27
  logicalPath: config/pic32mk_gp_db
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3F20C45547DA70F47ACA0F95C67AFE27
- generatedChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
  logicalPath: config/pic32mk_gp_db
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE5BCC6CEA2D57AF1B637918874FD32
- generatedChecksum: 2335C329F2EAF94F702818F1429DB49A
  logicalPath: config/pic32mk_gp_db
  name: interrupts_a.S
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2335C329F2EAF94F702818F1429DB49A
- generatedChecksum: 47F98BAFD5D2A077AB529D10DB870AFF
  logicalPath: FreeRTOS/Source
  name: list.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 47F98BAFD5D2A077AB529D10DB870AFF
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
  logicalPath: config/pic32mk_gp_db/osal
  name: osal_freertos.c
  physicalPath: osal
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8FDD6248506F28B32C4F5FD9AA0D9C6F
- generatedChecksum: 12589A4CA07B5ADDF405E28B3564A292
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 12589A4CA07B5ADDF405E28B3564A292
- generatedChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
- generatedChecksum: 7E6FB5B0DAA25855E1DB6A68B6ADCBFE
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7E6FB5B0DAA25855E1DB6A68B6ADCBFE
- generatedChecksum: 0E851159CFF7B40028D295108F0F7474
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MK
  name: port.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E851159CFF7B40028D295108F0F7474
- generatedChecksum: DF45E3DDDEC2F56707A9CBFBE9B8F3FD
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MK
  name: port_asm.S
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK
  security: NON_SECURE
  type: SOURCE
  userChecksum: DF45E3DDDEC2F56707A9CBFBE9B8F3FD
- generatedChecksum: 13259EE43A731BF0F46EA946229027BF
  logicalPath: FreeRTOS/Source
  name: queue.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 13259EE43A731BF0F46EA946229027BF
- generatedChecksum: A9BDA97498BEA85049883F48FB1094A0
  logicalPath: FreeRTOS/Source
  name: stream_buffer.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: A9BDA97498BEA85049883F48FB1094A0
- generatedChecksum: EA2F3541B981029BA9344F8814CB8527
  logicalPath: config/pic32mk_gp_db
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EA2F3541B981029BA9344F8814CB8527
- generatedChecksum: 2811D7C532CEFF995F8697FCED6A1C34
  logicalPath: FreeRTOS/Source
  name: timers.c
  physicalPath: ../../third_party/rtos/FreeRTOS/Source
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2811D7C532CEFF995F8697FCED6A1C34
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mk_gp_db/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 5E06C8C3B681B9398724569B7DC5AFB8
  logicalPath: FreeRTOS/Source/include
  name: FreeRTOS.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5E06C8C3B681B9398724569B7DC5AFB8
- generatedChecksum: 8DF2A49E7B6CC941FA3776D48DD58736
  logicalPath: config/pic32mk_gp_db
  name: FreeRTOSConfig.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DF2A49E7B6CC941FA3776D48DD58736
- generatedChecksum: E44F224CDF5B12B127F4CF2B074AD35D
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MK
  name: ISR_Support.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK
  security: NON_SECURE
  type: HEADER
  userChecksum: E44F224CDF5B12B127F4CF2B074AD35D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app1.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 566A4DDAD9C2CD458CA820E00953015C
  logicalPath: config/pic32mk_gp_db/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 566A4DDAD9C2CD458CA820E00953015C
- generatedChecksum: 7A852268CAA1F0FBB9E75D327532882A
  logicalPath: config/pic32mk_gp_db
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7A852268CAA1F0FBB9E75D327532882A
- generatedChecksum: 4B11D1A616E95BDD37123685C8434FCF
  logicalPath: FreeRTOS/Source/include
  name: croutine.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 4B11D1A616E95BDD37123685C8434FCF
- generatedChecksum: 42FA1070C152D7213D37402EA00CE521
  logicalPath: config/pic32mk_gp_db
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 42FA1070C152D7213D37402EA00CE521
- generatedChecksum: ACB7AD12FD525895ABA47C26F4F9A683
  logicalPath: FreeRTOS/Source/include
  name: deprecated_definitions.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: ACB7AD12FD525895ABA47C26F4F9A683
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_gp_db
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: DE52B71A2D274138117243B700F40B11
  logicalPath: FreeRTOS/Source/include
  name: event_groups.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: DE52B71A2D274138117243B700F40B11
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_gp_db
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 58875A2FBF6B0502B6D3B8B5C47F3815
  logicalPath: FreeRTOS/Source/include
  name: list.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 58875A2FBF6B0502B6D3B8B5C47F3815
- generatedChecksum: 5D9D0A05D32C97E2E625020E1795C7F1
  logicalPath: FreeRTOS/Source/include
  name: message_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 5D9D0A05D32C97E2E625020E1795C7F1
- generatedChecksum: A34AAAD9F0BD596E8FF78D86FD64F869
  logicalPath: FreeRTOS/Source/include
  name: mpu_prototypes.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: A34AAAD9F0BD596E8FF78D86FD64F869
- generatedChecksum: 2ECEDD5114F296955777187904C449C7
  logicalPath: FreeRTOS/Source/include
  name: mpu_wrappers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 2ECEDD5114F296955777187904C449C7
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mk_gp_db/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 167A43EFF8A31441EBF85AC77958A30B
  logicalPath: config/pic32mk_gp_db/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 167A43EFF8A31441EBF85AC77958A30B
- generatedChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
  logicalPath: config/pic32mk_gp_db/osal
  name: osal_freertos.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 9D6F205ECFDB2028C5CF766B52B5B7B2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: F666CF132ECA91F43C2A25389BA2AC28
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F666CF132ECA91F43C2A25389BA2AC28
- generatedChecksum: 2D4AF5453DDF4FB6D2C0CA57CD393E32
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 2D4AF5453DDF4FB6D2C0CA57CD393E32
- generatedChecksum: 8DD6C24BF18C96BDC016D9165DF88FEB
  logicalPath: FreeRTOS/Source/include
  name: portable.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 8DD6C24BF18C96BDC016D9165DF88FEB
- generatedChecksum: 94F2A78A46AC9F36C974B8E7BA09919F
  logicalPath: FreeRTOS/Source/portable/MPLAB/PIC32MK
  name: portmacro.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK
  security: NON_SECURE
  type: HEADER
  userChecksum: 94F2A78A46AC9F36C974B8E7BA09919F
- generatedChecksum: 99A9BD4D90230B49C97BBCEE121C1182
  logicalPath: FreeRTOS/Source/include
  name: projdefs.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 99A9BD4D90230B49C97BBCEE121C1182
- generatedChecksum: F917F55E280C54C23A7541A76AC34225
  logicalPath: FreeRTOS/Source/include
  name: queue.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: F917F55E280C54C23A7541A76AC34225
- generatedChecksum: D7426A4807316E4BB5540458F6F4C68F
  logicalPath: FreeRTOS/Source/include
  name: semphr.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: D7426A4807316E4BB5540458F6F4C68F
- generatedChecksum: 634A3DF879F184ABC5F96107F46AC4B2
  logicalPath: FreeRTOS/Source/include
  name: stack_macros.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 634A3DF879F184ABC5F96107F46AC4B2
- generatedChecksum: A652AC7D4938BE16F535BA3C90C86463
  logicalPath: FreeRTOS/Source/include
  name: stream_buffer.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: A652AC7D4938BE16F535BA3C90C86463
- generatedChecksum: 0A58B32A7058D0599EC5F6E3B33D42E6
  logicalPath: FreeRTOS/Source/include
  name: task.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 0A58B32A7058D0599EC5F6E3B33D42E6
- generatedChecksum: 41176F771D22559EFCE82398FCF33668
  logicalPath: FreeRTOS/Source/include
  name: timers.h
  physicalPath: ../../third_party/rtos/FreeRTOS/Source/include
  security: NON_SECURE
  type: HEADER
  userChecksum: 41176F771D22559EFCE82398FCF33668
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_gp_db
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: null
  logicalPath: config/pic32mk_gp_db
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 78F979907C866EDD174CB31208FC172B
  logicalPath: config/pic32mk_gp_db
  name: p32MK1024GPE100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 78F979907C866EDD174CB31208FC172B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-assembler
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mk_gp_db;
- append: true
  category: C32-AS
  delimiter: ;
  key: extra-include-directories-for-preprocessor
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;../src/third_party/rtos/FreeRTOS/Source/include;../src/config/pic32mk_gp_db;
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src/third_party/rtos/FreeRTOS/Source/portable/MPLAB/PIC32MK;../src/third_party/rtos/FreeRTOS/Source/include;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
