files:
- generatedChecksum: null
  logicalPath: ''
  name: app1.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app2.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 88EC0E8DE9765171A5719AD6829DF317
  logicalPath: config/pic32mk_mca_curiosity_pro/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 88EC0E8DE9765171A5719AD6829DF317
- generatedChecksum: F95D354CF700B247BF6F0F01B6353452
  logicalPath: config/pic32mk_mca_curiosity_pro/driver/usart
  name: drv_usart.c
  physicalPath: driver/usart/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: F95D354CF700B247BF6F0F01B6353452
- generatedChecksum: 872B12305821887C9AFF78A64839A20D
  logicalPath: config/pic32mk_mca_curiosity_pro/driver/usart
  name: drv_usart_local.h
  physicalPath: driver/usart/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 872B12305821887C9AFF78A64839A20D
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: 8F1B462DF9CDEBE760FFF642397D6DF8
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8F1B462DF9CDEBE760FFF642397D6DF8
- generatedChecksum: E91D95408DB5ED2DA1E6BE1F764D2659
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: E91D95408DB5ED2DA1E6BE1F764D2659
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 73D1E4FD15220DBC24D501EE9B15CA1D
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 73D1E4FD15220DBC24D501EE9B15CA1D
- generatedChecksum: 752FA47ACA60ED195B868C32C255B6D2
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 752FA47ACA60ED195B868C32C255B6D2
- generatedChecksum: B41D5D224A96F6A1772A7C38F3A37B8A
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: B41D5D224A96F6A1772A7C38F3A37B8A
- generatedChecksum: C5649F8709EE4CC01B3724FEB4793327
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: C5649F8709EE4CC01B3724FEB4793327
- generatedChecksum: AFE352183832B9FC4DB68BE3E459782F
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/uart
  name: plib_uart2.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: AFE352183832B9FC4DB68BE3E459782F
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mk_mca_curiosity_pro/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 508FC48635F015CCC559D883D01D99AB
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 508FC48635F015CCC559D883D01D99AB
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mk_mca_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: null
  logicalPath: ''
  name: app1.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: null
  logicalPath: ''
  name: app2.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: BBB513A95461DAF6965F56F3DAAE99C7
  logicalPath: config/pic32mk_mca_curiosity_pro/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: BBB513A95461DAF6965F56F3DAAE99C7
- generatedChecksum: A6BC53C09EEE7D7E6D641391C3A7123E
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: A6BC53C09EEE7D7E6D641391C3A7123E
- generatedChecksum: C6E5F57BF3CAAD70470F4EE35D1876FA
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: C6E5F57BF3CAAD70470F4EE35D1876FA
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mk_mca_curiosity_pro/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mk_mca_curiosity_pro/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: 32A69D3A36D95B996CA22CB89C5907DB
  logicalPath: config/pic32mk_mca_curiosity_pro/driver/usart
  name: drv_usart.h
  physicalPath: driver/usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 32A69D3A36D95B996CA22CB89C5907DB
- generatedChecksum: 6A33BD761891FC1DA0DA3D6899CD645F
  logicalPath: config/pic32mk_mca_curiosity_pro/driver/usart
  name: drv_usart_definitions.h
  physicalPath: driver/usart
  security: NON_SECURE
  type: HEADER
  userChecksum: 6A33BD761891FC1DA0DA3D6899CD645F
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mk_mca_curiosity_pro/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mk_mca_curiosity_pro/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mk_mca_curiosity_pro/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: B5377459A947965D398E898B7BECC090
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: B5377459A947965D398E898B7BECC090
- generatedChecksum: 30332B29B77DD9EF4435B6FD72138FDF
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 30332B29B77DD9EF4435B6FD72138FDF
- generatedChecksum: B2779866D186C91283DDF538D0E06774
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: B2779866D186C91283DDF538D0E06774
- generatedChecksum: 972290F4311D95247E55059A6CA4CE50
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/uart
  name: plib_uart2.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 972290F4311D95247E55059A6CA4CE50
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_mca_curiosity_pro/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: FADDA086C6C4E8FD7EBCE117438767A6
  logicalPath: config/pic32mk_mca_curiosity_pro/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: FADDA086C6C4E8FD7EBCE117438767A6
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mk_mca_curiosity_pro/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mk_mca_curiosity_pro/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mk_mca_curiosity_pro/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mk_mca_curiosity_pro/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mk_mca_curiosity_pro/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: null
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: AFEEF05303BA1755340AEA0C8E51A3C5
  logicalPath: config/pic32mk_mca_curiosity_pro
  name: p32MK0128MCA048.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: AFEEF05303BA1755340AEA0C8E51A3C5
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mca_curiosity_pro;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mca_curiosity_pro;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
