configName: pic32mk_mca_curiosity_pro
folderName: pic32mk_mca_curiosity_pro
format_version: v1.0
frameworkPath: ..\..\..\..\..\..\..\h3
processor: PIC32MK0128MCA048
projectName: at24_eeprom_read_write_pic32mk_mca_curiosity_pro
settings:
  PackageFilter: bootloader;bsp;cec173x_soteria_lib;core;crypto;csp;Devices;dev_packs;harmony-services;net;quick_docs;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-MC_DFP\1.10.146\atdf\PIC32MK0128MCA048.atdf
