configName: pic32mk_gp_db
folderName: ''
format_version: v1.0
frameworkPath: ../../../../..
processor: PIC32MK1024GPE100
projectName: ''
settings:
  PackageFilter: audio;bootloader;bsp;core;core_apps_pic32cz_ca;core_apps_sam_d21_da1;crypto;cryptoauthlib;csp;gfx;mbed_os_rtos;mbed_os_rtos_apps;micrium_ucos3;motor_control;net;touch;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MK-GP_DFP\1.6.140\atdf\PIC32MK1024GPE100.atdf
