files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D26088F21E3A03BD0AF1C72C387BDD81
  logicalPath: config/pic32mk_mcm_curiosity_pro/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: D26088F21E3A03BD0AF1C72C387BDD81
- generatedChecksum: 4F1E691F70878F4E114F5C6BDB4BD606
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/hardware_access
  name: diskio.c
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4F1E691F70878F4E114F5C6BDB4BD606
- generatedChecksum: 257ACC61A57EA8DE78BA7E1F78DB85A3
  logicalPath: config/pic32mk_mcm_curiosity_pro/driver/memory
  name: drv_memory.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 257ACC61A57EA8DE78BA7E1F78DB85A3
- generatedChecksum: AD5CAAD66A56C9B5D17EB7E756C22D0C
  logicalPath: config/pic32mk_mcm_curiosity_pro/driver/memory
  name: drv_memory_file_system.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: AD5CAAD66A56C9B5D17EB7E756C22D0C
- generatedChecksum: DC6BF3BD3BE8D60070E6CFAD73ECC6EF
  logicalPath: config/pic32mk_mcm_curiosity_pro/driver/memory
  name: drv_memory_nvm.c
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: DC6BF3BD3BE8D60070E6CFAD73ECC6EF
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: B2ADAD943E1B2BEEFF974468E2509BD5
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/file_system
  name: ff.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: B2ADAD943E1B2BEEFF974468E2509BD5
- generatedChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/file_system
  name: ffunicode.c
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9E153A6D4F8E0EA1F6901BAED7DD80FD
- generatedChecksum: 051F4DAEFACCDAF95287E809B16E4BC3
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 051F4DAEFACCDAF95287E809B16E4BC3
- generatedChecksum: B53E833BD00238A02201B408CD7E016C
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B53E833BD00238A02201B408CD7E016C
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: C211D16F2EF222C36C99074FD1BDB173
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: C211D16F2EF222C36C99074FD1BDB173
- generatedChecksum: B4D484C3EBFF7D6F68C22C87DD9D7504
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: B4D484C3EBFF7D6F68C22C87DD9D7504
- generatedChecksum: 427AB0BD956A52C4A257DE1F6DA0B0D6
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 427AB0BD956A52C4A257DE1F6DA0B0D6
- generatedChecksum: 7CD1EDDF64BB45965E2652000C1FBFF5
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/nvm
  name: plib_nvm.c
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7CD1EDDF64BB45965E2652000C1FBFF5
- generatedChecksum: 64197587C5A197FD05E94AB039A2DD66
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs
  name: sys_fs.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 64197587C5A197FD05E94AB039A2DD66
- generatedChecksum: 1F79CD9E378D98E657FCEB0552B2B659
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs
  name: sys_fs_fat_interface.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1F79CD9E378D98E657FCEB0552B2B659
- generatedChecksum: 8A608E11F4981AA9CC52EA5EF5C76F4A
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs
  name: sys_fs_media_manager.c
  physicalPath: system/fs/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8A608E11F4981AA9CC52EA5EF5C76F4A
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: 22CA1BA8315F3E404A8BD8B5BD0C04CF
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 22CA1BA8315F3E404A8BD8B5BD0C04CF
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mk_mcm_curiosity_pro/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 60CCF2FCB84A0FA9AA8C1607725D47A4
  logicalPath: config/pic32mk_mcm_curiosity_pro/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 60CCF2FCB84A0FA9AA8C1607725D47A4
- generatedChecksum: FE90AFCD0B52895BB1F44494EB37BFE3
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: FE90AFCD0B52895BB1F44494EB37BFE3
- generatedChecksum: 45789B163EC51658512979B364D8D64E
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 45789B163EC51658512979B364D8D64E
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 630DFA1824A5279838B4330DA2FF3E5E
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/hardware_access
  name: diskio.h
  physicalPath: system/fs/fat_fs/hardware_access
  security: NON_SECURE
  type: HEADER
  userChecksum: 630DFA1824A5279838B4330DA2FF3E5E
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config/pic32mk_mcm_curiosity_pro/driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config/pic32mk_mcm_curiosity_pro/driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: EFD9CC847D820C0DCC84B3877B8FA415
  logicalPath: config/pic32mk_mcm_curiosity_pro/driver/memory
  name: drv_memory.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: EFD9CC847D820C0DCC84B3877B8FA415
- generatedChecksum: 8BF1EFFCD7DC02480C27F3DE35FB5009
  logicalPath: config/pic32mk_mcm_curiosity_pro/driver/memory
  name: drv_memory_definitions.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: 8BF1EFFCD7DC02480C27F3DE35FB5009
- generatedChecksum: 2E25CEFA28CCA2CD66BA9DF6B4C66621
  logicalPath: config/pic32mk_mcm_curiosity_pro/driver/memory
  name: drv_memory_local.h
  physicalPath: driver/memory/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 2E25CEFA28CCA2CD66BA9DF6B4C66621
- generatedChecksum: D7B4ABDE58DE140171E13AF1B3C3292A
  logicalPath: config/pic32mk_mcm_curiosity_pro/driver/memory
  name: drv_memory_nvm.h
  physicalPath: driver/memory
  security: NON_SECURE
  type: HEADER
  userChecksum: D7B4ABDE58DE140171E13AF1B3C3292A
- generatedChecksum: 2D3A9FC37968F5000CB45C6B4AD965D6
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/file_system
  name: ff.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: 2D3A9FC37968F5000CB45C6B4AD965D6
- generatedChecksum: D9A040CE610ED3F9283F4BA6A13DADF9
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/file_system
  name: ffconf.h
  physicalPath: system/fs/fat_fs/file_system
  security: NON_SECURE
  type: HEADER
  userChecksum: D9A040CE610ED3F9283F4BA6A13DADF9
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mk_mcm_curiosity_pro/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mk_mcm_curiosity_pro/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mk_mcm_curiosity_pro/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 4D592E1C42727324FE2F5EB681F6C5AA
- generatedChecksum: 3BF8A756C9D5530BD1CF50D143DF09DF
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3BF8A756C9D5530BD1CF50D143DF09DF
- generatedChecksum: F8956D879D4FFD1B8EE29940C3057795
  logicalPath: config/pic32mk_mcm_curiosity_pro/peripheral/nvm
  name: plib_nvm.h
  physicalPath: peripheral/nvm
  security: NON_SECURE
  type: HEADER
  userChecksum: F8956D879D4FFD1B8EE29940C3057795
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 4A8DA7BC60B438CE161462CB299CCC9D
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs
  name: sys_fs.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 4A8DA7BC60B438CE161462CB299CCC9D
- generatedChecksum: 0D9FE9035E3AA8082C5657240106F2DC
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs
  name: sys_fs_fat_interface.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D9FE9035E3AA8082C5657240106F2DC
- generatedChecksum: 0D162D1868A187FDC092657020E668D8
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs
  name: sys_fs_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: 0D162D1868A187FDC092657020E668D8
- generatedChecksum: D0DEC824B933722219A05F00A4CD5BB4
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs
  name: sys_fs_media_manager.h
  physicalPath: system/fs
  security: NON_SECURE
  type: HEADER
  userChecksum: D0DEC824B933722219A05F00A4CD5BB4
- generatedChecksum: E50782BD59B15F2EAAF53AAD818793EE
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/fs
  name: sys_fs_media_manager_local.h
  physicalPath: system/fs/src
  security: NON_SECURE
  type: HEADER
  userChecksum: E50782BD59B15F2EAAF53AAD818793EE
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mk_mcm_curiosity_pro/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mk_mcm_curiosity_pro/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mk_mcm_curiosity_pro/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: A1CB3454D5A9393479E09211BEEDDD49
  logicalPath: config/pic32mk_mcm_curiosity_pro/system
  name: system_media.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: A1CB3454D5A9393479E09211BEEDDD49
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mk_mcm_curiosity_pro/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: D952D84078461ACADCCC56F030F63840
  logicalPath: config/pic32mk_mcm_curiosity_pro
  name: p32MK1024MCM100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: D952D84078461ACADCCC56F030F63840
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/file_system;../src/config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/hardware_access
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_mcm_curiosity_pro;
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ;../src/config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/file_system;../src/config/pic32mk_mcm_curiosity_pro/system/fs/fat_fs/hardware_access
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
