format_version: v1.0
type: UniqueComponent
attributes: {id: i2c_bb}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: I2CBB_CONNECTED_TIMER}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: i2c_bb, value: TMR2}
  - type: KeyValueSet
    attributes: {id: I2CBB_SCL_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '14'}
  - type: KeyValueSet
    attributes: {id: I2CBB_SDA_PIN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4'}
- type: Attachments
  children:
  - type: DirectCapability
    attributes: {id: I2C}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: drv_i2c_0}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: drv_i2c_I2C_dependency}
  - type: DirectDependency
    attributes: {id: TMR}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: tmr2}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: TMR2_TMR}
- type: ElementPosition
  attributes: {x: '181', y: '96', id: i2c_bb}
