files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D26088F21E3A03BD0AF1C72C387BDD81
  logicalPath: config\pic32mk_gp_db\bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: D26088F21E3A03BD0AF1C72C387BDD81
- generatedChecksum: B47C99F991BD0A4FF643CE6D253133D9
  logicalPath: config\pic32mk_gp_db\driver\at25
  name: drv_at25.c
  physicalPath: driver\at25\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: B47C99F991BD0A4FF643CE6D253133D9
- generatedChecksum: E520334770AE8B4BD498BDBB000B7086
  logicalPath: config\pic32mk_gp_db\driver\at25
  name: drv_at25_local.h
  physicalPath: driver\at25\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: E520334770AE8B4BD498BDBB000B7086
- generatedChecksum: EC410AF32A00CC5E9DF0F879297B47F1
  logicalPath: config\pic32mk_gp_db
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EC410AF32A00CC5E9DF0F879297B47F1
- generatedChecksum: D3C031BE3F661C83170A25DD7769B795
  logicalPath: config\pic32mk_gp_db
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D3C031BE3F661C83170A25DD7769B795
- generatedChecksum: D08F8170A39E1E6C2E4FD2D60167EA1F
  logicalPath: config\pic32mk_gp_db
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: D08F8170A39E1E6C2E4FD2D60167EA1F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: A490BDC3DCE0D5E60E4A3C35E15A1808
  logicalPath: config\pic32mk_gp_db\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: A490BDC3DCE0D5E60E4A3C35E15A1808
- generatedChecksum: E3512475F737467E8DAC34A58F0E172E
  logicalPath: config\pic32mk_gp_db\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: E3512475F737467E8DAC34A58F0E172E
- generatedChecksum: 76C1291A03D66DFB58CEE5D14AD4155C
  logicalPath: config\pic32mk_gp_db\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 76C1291A03D66DFB58CEE5D14AD4155C
- generatedChecksum: 0864AC7C5CD2A041E71E8ABE12F1DEBF
  logicalPath: config\pic32mk_gp_db\peripheral\spi\spi_master
  name: plib_spi6_master.c
  physicalPath: peripheral\spi\spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0864AC7C5CD2A041E71E8ABE12F1DEBF
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config\pic32mk_gp_db\system\int
  name: sys_int.c
  physicalPath: system\int\src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config\pic32mk_gp_db
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mk_gp_db\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ..\..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 3FEAC95DFD4DE6C583AAACC2E785135D
  logicalPath: config\pic32mk_gp_db\bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 3FEAC95DFD4DE6C583AAACC2E785135D
- generatedChecksum: 4468F9856F09A3BC440FBC996D519992
  logicalPath: config\pic32mk_gp_db
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4468F9856F09A3BC440FBC996D519992
- generatedChecksum: D7902D6419661562BFD9535BA17A08B6
  logicalPath: config\pic32mk_gp_db
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D7902D6419661562BFD9535BA17A08B6
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mk_gp_db
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 1D2094DFA60F847FFD4E8153B6E78027
  logicalPath: config\pic32mk_gp_db\driver
  name: driver.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: 1D2094DFA60F847FFD4E8153B6E78027
- generatedChecksum: CC7DFCC51CD25171A3E400E18969354F
  logicalPath: config\pic32mk_gp_db\driver
  name: driver_common.h
  physicalPath: driver
  security: NON_SECURE
  type: HEADER
  userChecksum: CC7DFCC51CD25171A3E400E18969354F
- generatedChecksum: D88B31F2549366FA45428169AED5AA1B
  logicalPath: config\pic32mk_gp_db\driver\at25
  name: drv_at25.h
  physicalPath: driver\at25
  security: NON_SECURE
  type: HEADER
  userChecksum: D88B31F2549366FA45428169AED5AA1B
- generatedChecksum: 3A5673768ECF05CBFC6F33D688186538
  logicalPath: config\pic32mk_gp_db\driver\at25
  name: drv_at25_definitions.h
  physicalPath: driver\at25
  security: NON_SECURE
  type: HEADER
  userChecksum: 3A5673768ECF05CBFC6F33D688186538
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mk_gp_db
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config\pic32mk_gp_db\osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config\pic32mk_gp_db\osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config\pic32mk_gp_db\osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mk_gp_db\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: F666CF132ECA91F43C2A25389BA2AC28
  logicalPath: config\pic32mk_gp_db\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F666CF132ECA91F43C2A25389BA2AC28
- generatedChecksum: 1B551A3FADA0C3A4C0281048BB7F21AA
  logicalPath: config\pic32mk_gp_db\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 1B551A3FADA0C3A4C0281048BB7F21AA
- generatedChecksum: 50E9AD2D0F7881C540C3CBF286F203A0
  logicalPath: config\pic32mk_gp_db\peripheral\spi\spi_master
  name: plib_spi6_master.h
  physicalPath: peripheral\spi\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 50E9AD2D0F7881C540C3CBF286F203A0
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config\pic32mk_gp_db\peripheral\spi\spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral\spi\spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: 6972608768DDBE6E37A2D81B83DF490B
  logicalPath: config\pic32mk_gp_db\system\debug
  name: sys_debug.h
  physicalPath: system\debug
  security: NON_SECURE
  type: HEADER
  userChecksum: 6972608768DDBE6E37A2D81B83DF490B
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config\pic32mk_gp_db\system\int
  name: sys_int.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config\pic32mk_gp_db\system\int
  name: sys_int_mapping.h
  physicalPath: system\int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: C02BABD057471C3A90878ED3FD51403F
  logicalPath: config\pic32mk_gp_db\system\ports
  name: sys_ports.h
  physicalPath: system\ports
  security: NON_SECURE
  type: HEADER
  userChecksum: C02BABD057471C3A90878ED3FD51403F
- generatedChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
  logicalPath: config\pic32mk_gp_db\system\ports
  name: sys_ports_mapping.h
  physicalPath: system\ports
  security: NON_SECURE
  type: HEADER
  userChecksum: BC6E1661BF4CAC21B70F5F56A0D7BBDB
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config\pic32mk_gp_db\system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config\pic32mk_gp_db\system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config\pic32mk_gp_db\system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mk_gp_db
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: null
  logicalPath: config\pic32mk_gp_db
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 2773C35D00AC364A265E124C19ECDFDD
  logicalPath: config\pic32mk_gp_db
  name: p32MK1024GPE100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 2773C35D00AC364A265E124C19ECDFDD
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;../src/packs/PIC32MK1024GPE100_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;../src/packs/PIC32MK1024GPE100_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
