files:
- generatedChecksum: null
  logicalPath: ''
  name: app.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: D26088F21E3A03BD0AF1C72C387BDD81
  logicalPath: config/pic32mk_gp_db/bsp
  name: bsp.c
  physicalPath: bsp
  security: NON_SECURE
  type: SOURCE
  userChecksum: D26088F21E3A03BD0AF1C72C387BDD81
- generatedChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
  logicalPath: config/pic32mk_gp_db
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4BBDE3B7B0DAEE2CA5A8F519001D5BFF
- generatedChecksum: 161A4A1A7583DA896DF680B0620675D1
  logicalPath: config/pic32mk_gp_db
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 161A4A1A7583DA896DF680B0620675D1
- generatedChecksum: 9BA69C3C02FBBF44409B8122F584883D
  logicalPath: config/pic32mk_gp_db
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9BA69C3C02FBBF44409B8122F584883D
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 7CA6FDF1D618DDC3A6ECBB9742A869C3
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7CA6FDF1D618DDC3A6ECBB9742A869C3
- generatedChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
  logicalPath: config/pic32mk_gp_db/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2FEFEA0D4E94F5A5F3D76BAEC3D602E5
- generatedChecksum: 44B0E07A6581B9007D018C26486AB784
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 44B0E07A6581B9007D018C26486AB784
- generatedChecksum: B4D7353560FF34446F1BA2242D2ED180
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: B4D7353560FF34446F1BA2242D2ED180
- generatedChecksum: 093F2A355E118F6613BDD8A9342378DF
  logicalPath: config/pic32mk_gp_db/peripheral/uart
  name: plib_uart6.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 093F2A355E118F6613BDD8A9342378DF
- generatedChecksum: C95CE0ABB86E6B11CF77E8891D294510
  logicalPath: config/pic32mk_gp_db/system/int
  name: sys_int.c
  physicalPath: system/int/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: C95CE0ABB86E6B11CF77E8891D294510
- generatedChecksum: AD9DEEA019A0C5B587E2066874A0499D
  logicalPath: config/pic32mk_gp_db/system/time
  name: sys_time.c
  physicalPath: system/time/src
  security: NON_SECURE
  type: SOURCE
  userChecksum: AD9DEEA019A0C5B587E2066874A0499D
- generatedChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
  logicalPath: config/pic32mk_gp_db
  name: tasks.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DE51BB8F6FDBC39FB049CB2A14E56B25
- generatedChecksum: 8D0C633B8061C12CF522123C4B98475C
  logicalPath: config/pic32mk_gp_db/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8D0C633B8061C12CF522123C4B98475C
- generatedChecksum: null
  logicalPath: ''
  name: app.h
  physicalPath: ../..
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 566A4DDAD9C2CD458CA820E00953015C
  logicalPath: config/pic32mk_gp_db/bsp
  name: bsp.h
  physicalPath: bsp
  security: NON_SECURE
  type: HEADER
  userChecksum: 566A4DDAD9C2CD458CA820E00953015C
- generatedChecksum: 633BB23036C3D1D81EE59184C3F5633E
  logicalPath: config/pic32mk_gp_db
  name: configuration.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 633BB23036C3D1D81EE59184C3F5633E
- generatedChecksum: D8C0ACD91A51541031F46F58AF11C434
  logicalPath: config/pic32mk_gp_db
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: D8C0ACD91A51541031F46F58AF11C434
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_gp_db
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mk_gp_db
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: F0AD88762263B7CB89B02AB4F5876059
  logicalPath: config/pic32mk_gp_db/osal
  name: osal.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: F0AD88762263B7CB89B02AB4F5876059
- generatedChecksum: 0AC88C49E4585B606FD5AC6804F0C340
  logicalPath: config/pic32mk_gp_db/osal
  name: osal_definitions.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: 0AC88C49E4585B606FD5AC6804F0C340
- generatedChecksum: B040122CCA94A0636810D6F15F13B751
  logicalPath: config/pic32mk_gp_db/osal
  name: osal_impl_basic.h
  physicalPath: osal
  security: NON_SECURE
  type: HEADER
  userChecksum: B040122CCA94A0636810D6F15F13B751
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mk_gp_db/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 07119F033620347F2C491F50E3F62AFC
  logicalPath: config/pic32mk_gp_db/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 07119F033620347F2C491F50E3F62AFC
- generatedChecksum: F666CF132ECA91F43C2A25389BA2AC28
  logicalPath: config/pic32mk_gp_db/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: F666CF132ECA91F43C2A25389BA2AC28
- generatedChecksum: 2D4AF5453DDF4FB6D2C0CA57CD393E32
  logicalPath: config/pic32mk_gp_db/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 2D4AF5453DDF4FB6D2C0CA57CD393E32
- generatedChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
  logicalPath: config/pic32mk_gp_db/peripheral/uart
  name: plib_uart6.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C0D30955FCB8BEFE0E3AC5103F57776
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mk_gp_db/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: FADDA086C6C4E8FD7EBCE117438767A6
  logicalPath: config/pic32mk_gp_db/system/debug
  name: sys_debug.h
  physicalPath: system/debug
  security: NON_SECURE
  type: HEADER
  userChecksum: FADDA086C6C4E8FD7EBCE117438767A6
- generatedChecksum: 47330C2D8F204B2B69F8A86240A564B6
  logicalPath: config/pic32mk_gp_db/system/int
  name: sys_int.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: 47330C2D8F204B2B69F8A86240A564B6
- generatedChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
  logicalPath: config/pic32mk_gp_db/system/int
  name: sys_int_mapping.h
  physicalPath: system/int
  security: NON_SECURE
  type: HEADER
  userChecksum: FC7B55936A09E0CA1395AE4DFB1A188F
- generatedChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
  logicalPath: config/pic32mk_gp_db/system/time
  name: sys_time.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 466D676839280C0E7FC2CC6F78BA6EE9
- generatedChecksum: 9463F9BBF69C9593FF3B30F8BC587234
  logicalPath: config/pic32mk_gp_db/system/time
  name: sys_time_definitions.h
  physicalPath: system/time
  security: NON_SECURE
  type: HEADER
  userChecksum: 9463F9BBF69C9593FF3B30F8BC587234
- generatedChecksum: C7A6D8C5408A42EB1CD2CB277E6EFBF4
  logicalPath: config/pic32mk_gp_db/system/time
  name: sys_time_local.h
  physicalPath: system/time/src
  security: NON_SECURE
  type: HEADER
  userChecksum: C7A6D8C5408A42EB1CD2CB277E6EFBF4
- generatedChecksum: BE95B4F134C5C929787B9DA6FDBF3501
  logicalPath: config/pic32mk_gp_db/system
  name: system.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: BE95B4F134C5C929787B9DA6FDBF3501
- generatedChecksum: C3F5136D520DAC4416512EBFCCA023C3
  logicalPath: config/pic32mk_gp_db/system
  name: system_common.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: C3F5136D520DAC4416512EBFCCA023C3
- generatedChecksum: 1C75A8A6B60598A2FD0D533F57839B72
  logicalPath: config/pic32mk_gp_db/system
  name: system_module.h
  physicalPath: system
  security: NON_SECURE
  type: HEADER
  userChecksum: 1C75A8A6B60598A2FD0D533F57839B72
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mk_gp_db
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: null
  logicalPath: config/pic32mk_gp_db
  name: user.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: null
- generatedChecksum: 78F979907C866EDD174CB31208FC172B
  logicalPath: config/pic32mk_gp_db
  name: p32MK1024GPE100.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 78F979907C866EDD174CB31208FC172B
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_db;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
